name: Build Release

on:
  release:
    types: [published]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v3

      - name: Setup Python 3.12
        run: uv python install 3.12

      - name: Install dependencies
        run: uv pip install --refresh --strict --link-mode=copy zstandard pyside6 leveldb-py nuitka imageio --system

      - name: Build with Nuitka (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          python -m nuitka --onefile --output-dir=dist ^
            --company-name="Zuko [@tansautn]"  ^
            --product-name="LevelDB Viewer | Z U K O" ^
            --file-version="2026.1.0.0" ^
            --product-version="1.0.0" ^
            --copyright="© 2026 (Z) Programing" ^
            --trademarks="Z U K O ®" ^
            --plugin-enable=pyside6 ^
            --windows-console-mode=disable ^
            --windows-icon-from-ico=assets/icon.png ./src/leveldb-viewer.py

      - name: Build with Nuitka (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          python -m nuitka --onefile --output-dir=dist \
            --plugin-enable=pyside6 \
            ./src/leveldb-viewer.py

      - name: Build with Nuitka (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          python -m nuitka --standalone --macos-create-app-bundle --output-dir=dist \
            --plugin-enable=pyside6 \
            ./src/leveldb-viewer.py
          cd dist
          zip -r leveldb-viewer-macos.zip leveldb-viewer.app

      - name: Prepare Artifacts (Linux/Windows)
        if: matrix.os != 'macos-latest'
        shell: bash
        run: |
          mkdir -p artifacts
          cp dist/leveldb-viewer* artifacts/

      - name: Prepare Artifacts (macOS)
        if: matrix.os == 'macos-latest'
        shell: bash
        run: |
          mkdir -p artifacts
          cp dist/leveldb-viewer-macos.zip artifacts/

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*
